name: Build project with Maven
on:
  pull_request:
  push:
    branches-ignore: [master]
  schedule:
  - cron: '2 2 * * 1-5' # run nightly master builds on weekdays

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Import Secrets
      uses: RichiCoder1/vault-action@v0.10.2
      with:
        url: ${{ secrets.VAULT_ADDR }}
        method: approle
        roleId: ${{ secrets.VAULT_ROLE_ID }}
        secretId: ${{ secrets.VAULT_SECRET_ID }}
        secrets: |
          common/github.com/actions/camunda NEXUS_PSW | NEXUS_PSW;
          common/github.com/actions/camunda NEXUS_USR | NEXUS_USR;
